services:
  - type: web
    name: taptaptips-api
    env: docker
    plan: starter
    healthCheckPath: /actuator/health
    autoDeploy: true
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: taptaptips-db
          property: connectionString
      - key: JAVA_TOOL_OPTIONS
        value: "-XX:+AlwaysActAsServerClassMachine -XX:+UseContainerSupport -Xms256m -Xmx512m"
    dockerfilePath: ./Dockerfile

databases:
  - name: taptaptips-db
    plan: starter
