spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taptaptips
    username: postgres
    password: password

jwt:
  issuer: taptaptips
  accessTtlMinutes: 15
  refreshTtlDays: 14
  secret: dev-only-change-me

crypto:
  bank:
    key-base64: "dev-key-here"
