server:
  address: 0.0.0.0
  port: ${PORT:8080}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:${DATABASE_URL}}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.format_sql: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,logfile

jwt:
  issuer: taptaptips
  accessTtlMinutes: 15
  refreshTtlDays: 14
  secret: ${JWT_SECRET}

crypto:
  bank:
    key-base64: ${CRYPTO_BANK_KEY_BASE64}
